-- V3: Seed data — admin account, 10 movies from TMDB, 2 halls, 4 showtimes.
--
-- Admin credentials: admin@jeelpay.com / admin  (BCrypt hash below)
-- Movies were fetched once from TMDB and committed here; TMDB is not queried
-- at runtime.  Showtimes are set to July 2026 so they remain in the future.

-- ── Admin user ────────────────────────────────────────────────────────────────
INSERT INTO users (email, password_hash, role)
VALUES ('admin@jeelpay.com',
        '$2a$10$qSveaJc6RN7VrJyPY6ZRVeBI/tEYhK876dhuNp3g/ammlfytsUkiG',
        'ADMIN');

-- ── 10 Movies (TMDB) ─────────────────────────────────────────────────────────
INSERT INTO movies (tmdb_id, title, synopsis, poster_url, runtime_minutes, genres, release_year, rating) VALUES
(157336, 'Interstellar',
 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 169, 'Adventure, Drama, Science Fiction', 2014, 8.4),

(27205, 'Inception',
 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception".',
 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg', 148, 'Action, Science Fiction, Adventure', 2010, 8.4),

(155, 'The Dark Knight',
 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 152, 'Drama, Action, Crime, Thriller', 2008, 8.5),

(693134, 'Dune: Part Two',
 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2IGcgTow2.jpg', 167, 'Science Fiction, Adventure', 2024, 8.3),

(324857, 'Spider-Man: Into the Spider-Verse',
 'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', 117, 'Action, Adventure, Animation, Science Fiction', 2018, 8.4),

(11, 'Star Wars',
 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess.',
 'https://image.tmdb.org/t/p/w500/6FfCtSchYvwP61h1CbyI81Pte36.jpg', 121, 'Adventure, Action, Science Fiction', 1977, 8.2),

(122, 'The Lord of the Rings: The Return of the King',
 'Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron''s forces.',
 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 201, 'Adventure, Fantasy, Action', 2003, 8.5),

(24428, 'The Avengers',
 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster.',
 'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmja8y.jpg', 143, 'Science Fiction, Action, Adventure', 2012, 7.7),

(671, 'Harry Potter and the Philosopher''s Stone',
 'Harry Potter has lived under the stairs at his aunt and uncle''s house his whole life. But on his 11th birthday, he learns he''s a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry.',
 'https://image.tmdb.org/t/p/w500/wuMc08JTKEi69OsSRFOhNVVQAGC.jpg', 152, 'Adventure, Fantasy', 2001, 7.9),

(550, 'Fight Club',
 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', 139, 'Drama', 1999, 8.4);

-- ── 2 Halls ───────────────────────────────────────────────────────────────────
-- Hall 1: 4 rows (A–D) × 8 seats = 32 seats
INSERT INTO halls (name, total_rows, seats_per_row) VALUES ('Hall 1', 4, 8);
-- Hall 2: 5 rows (A–E) × 10 seats = 50 seats
INSERT INTO halls (name, total_rows, seats_per_row) VALUES ('Hall 2', 5, 10);

-- ── Showtimes (future dates — July/August 2026) ────────────────────────────
-- Seats are generated by V4; showtime_seats are also populated by V4.
INSERT INTO showtimes (movie_id, hall_id, start_time, price) VALUES
(1, 1, '2026-07-04 20:00:00', 45.00),   -- Interstellar, Hall 1
(2, 2, '2026-07-04 22:30:00', 45.00),   -- Inception, Hall 2
(3, 1, '2026-07-05 18:00:00', 50.00),   -- The Dark Knight, Hall 1
(4, 2, '2026-07-05 21:00:00', 50.00),   -- Dune: Part Two, Hall 2
(5, 1, '2026-08-01 20:00:00', 45.00),   -- Spider-Man, Hall 1
(6, 2, '2026-08-01 22:00:00', 45.00);   -- Star Wars, Hall 2
